### ISSUE TITLE
Remove advertising

### ISSUE THREAD

**Issue by pcjl** [vartan/robin-grow#38] opened 2016-04-02 00:52 UTC
I get that the script doesn't send "[Robin-Grow] I automatically voted to grow, and so can you! http://redd.it/4cwk2s !" multiple times in the same chat, but it's still annoying. Could you get rid of this?

**Comment by vartan** [comment] 2016-04-02 00:54
Duplicate of. #23

**Closed as completed** 2016-04-02 00:54 UTC
